CREATE TABLE PRODUCT 
(
  PK LONG NOT NULL 
, NAZWA VARCHAR2(50) NOT NULL 
, OPIS VARCHAR2(500) 
, CENA NUMBER DEFAULT 0 NOT NULL 
, ILOSC_SZTUK NUMBER DEFAULT 0 NOT NULL 
, CONSTRAINT PRODUCT_PK PRIMARY KEY 
  (
    PK 
  )
  ENABLE 
);
